# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        env:
            CI: false
        strategy:
            matrix:
                node-version: [12.6]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                  node --version
                  npm --version
            - name: set @bitregistry translation-help
              run: npm config set '@bit:registry' https://node.bit.dev
            
            - name: npm install
              run: npm ci
              
            - name: set max memory allocation
              run: export NODE_OPTIONS=–max_old_space_size=4096
            
            - name: build
              id: build
              run: |
                  npm run build

            - name: package
              id: package
              run: |
                  npm run electron-pack

            - name: Cleanup artifacts
              run: |
                  npx rimraf "dist/!(*.deb|*.AppImage|*.dmg)"
            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ matrix.os }}
                  path: dist

    build-windows:
        runs-on: ${{ matrix.os }}
        env:
            CI: false
        strategy:
            matrix:
                node-version: [12.6]
                os: [windows-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                  node --version
                  npm --version
                  
            - name: set @bitregistry translation-help
              run: npm config set '@bit:registry' https://node.bit.dev
            
            - name: npm install
              run: npm ci
            
            - name: set max memory allocation
              run: set NODE_OPTIONS=–max_old_space_size=4096
            
            - name: build
              id: build
              run: |
                  npm run build

            - name: packaging
              id: packaging
              run: |
                  npm run electron-pack
                  
            - name: Cleanup artifacts
              if: matrix.os != 'windows-latest'
              run: |
                  mkdir artifacts
                  mv "dist/(*.exe,*.deb,*.AppImage,*.dmg)" artifacts || true
            - name: Cleanup artifacts Win
              if: matrix.os == 'windows-latest'
              run: |
                  mkdir artifacts
                  mv dist/*.exe artifacts
            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: ${{matrix.os}}
                  path: artifacts
